name: ikirengaauto
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  page_transition: ^2.0.9
  country_code_picker: ^3.0.0
  pin_code_fields: ^7.4.0
  google_nav_bar: ^5.0.6
  provider: ^6.0.5
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  fluttertoast: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Ikirenga
      fonts:
        - asset: fonts/Ikirenga.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-Italic.ttf
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
    - family: Lato
      fonts:
        - asset: fonts/lato/Lato-Regular.ttf
        - asset: fonts/lato/Lato-Bold.ttf
        - asset: fonts/lato/Lato-Italic.ttf
        - asset: fonts/lato/Lato-BoldItalic.ttf
